# Generated by Django 5.2.1 on 2025-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(max_length=10, unique=True)),
                ('slot_group', models.CharField(blank=True, max_length=10, null=True)),
                ('slot_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=10)),
                ('slot_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VISITOR', 'Visitor'), ('GUEST', 'Guest/VIP')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('FREED', 'Freed'), ('REALLOCATED', 'Reallocated')], default='AVAILABLE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=10)),
            ],
        ),
    ]
