# Generated by Django 5.2.1 on 2025-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VISITOR', 'Visitor'), ('GUEST', 'Guest/VIP')], max_length=10)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('pass_type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('slot_code', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_EXTENSION', 'Pending Extension'), ('EXTENDED', 'Extended'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('arrived', models.BooleanField(default=False)),
                ('extension_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
